### ISSUE TITLE
Criar func de cadastro

### ISSUE THREAD

**Issue by BrunoItacaramby** [massudy/Mini-Projeto#16]
Pronto, definido

- [x] #17

- [x] #18

- [x] Criar code generator em ./useful/codegenarator.js 

- [x] #20

- [x] #21

- [x] #24

**Comment by BrunoItacaramby** [comment]
Quem eu vou cadastrar aqui? Quais os modelos mongoose?

**Comment by massudy** [comment]
Bruno, acho que agt pode fazer uma plataforma que cadastra restaurantes, então modemos criar os seguintes modelos mongoose

RestaurantOwner {
ID : string
Nome : string
}

Restaurante {
ID : string
OwnerID : string
Nome : string
Telefone : string
}

**Comment by BrunoItacaramby** [comment]
Pronto, definido

- [ ] Criar conexao com mongoose

- [ ] Criar os modelos mongoose

- [ ] Criar o CRUD de criaçao de Restaurante

- [ ] Criar o CRUD de criaçao de RestaurantOwner

- [ ] Finalizar criando a func de cadastro

**Comment by BrunoItacaramby** [comment]
FINALIZADO!!

#26
