### ISSUE TITLE
Criar a instancia do appbot

### ISSUE THREAD

**Issue by BrunoItacaramby** [massudy/Mini-Projeto#9]

**Comment by massudy** [comment]
legal bruno, vi que vc vai fazer, arrebenta
um dica pra ir mais rapido, é copiar do bot passado gogogo

**Comment by BrunoItacaramby** [comment]
Não to conseguindo fazer a instancia do appbot, pq tem q colocar o Type Module
![image](https://user-images.githubusercontent.com/116533235/197446927-4be2cb27-2721-429f-b18f-57c0368e0649.png)

**Comment by massudy** [comment]
Pronto bruno, bug resolvido
da um git pull e continua a featura, manda bala tmj
